### ISSUE TITLE
Temperature sensor shown in wrong orientation on 2.69

### ISSUE THREAD

**Issue by sym0nd0** [OpenSourceDistilling/The_Jeffrey_PCB#2]
Not sure if this project has been abandoned  or not. 

The temp sensor orientation is shown incorrectly on the silkscreen of the PCB, mounting it as shown results in the sensor burning out.

**Comment by PharmaJap** [comment]
Where did you get your sensors? All 5 of mine are mounted in the silkscreened direction (flat side towards the bottom, so that the curved side matches the petling), and are reporting temps correctly. The square solder point is GND, which matches the usual pinout of the DS18B20.

**Comment by sym0nd0** [comment]
Closed as project abandoned.
